### ISSUE TITLE
帅哥，能求一下脚本么。Virginia-analysis

### ISSUE THREAD

**Issue by kisspanda** [KangMing-ux/CTFs-Crypto#1]
最近打比赛，都是线下离线比赛，我发现大神的解题思路中有个脚本。堪称线下无网环境中的神器。

所以想求一下。。。。

**Comment by KangMing-ux** [comment]
Sorry, some files have been deleted by mistake. can you leave your email so that I can send it to you!

**Comment by kisspanda** [comment]
> Sorry, some files have been deleted by mistake. can you leave your email so that I can send it to you!



thx~~~~

有什么其他的CTF相关脚本，也不惜赐教。。。感谢感谢
